# Copyright (c) 2023 Cisco Systems, Inc. and its affiliates
# All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http:www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: awi.app-net-interface.io/v1alpha1
kind: ServiceConnection   #ExternalConnection
metadata:
  name: egress
spec:
  direction: egress # egress | ingress 
  name: my-db-service
  Source:
    name: finance-web-app
    subnets: ["173.0.0.0/24","40.10.5.0/28"]
    labels: # Use only when access is from a known kubernetes cluster.
      environment: "production"
      type : "database" 
  Destination:
    #ServiceType: external # external | lb | ingress  
    FQDN: localsvc1.k8s.com # valid fqdn (eg. www.microsoft.com)
    ConnectionIdentifiers:
      - name: "standard port"
        port: 8443
        protocol: tcp
      - name: "ssl1"
        port: 443
        protocol: tcp 