apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "awi-catalyst-sdwan-k8s-operator.fullname" . }}-manager-config
  labels:
  {{- include "awi-catalyst-sdwan-k8s-operator.labels" . | nindent 4 }}
data:
  controller_manager_config.yaml: {{ .Values.managerConfig.controllerManagerConfigYaml
    | toYaml | indent 1 }}